[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxMessageSize = 500
maxUploadSize = 200

[browser]
gatherUsageStats = false

[logger]
level = "error"

[global]
developmentMode = false

[client]
showErrorDetails = false

[theme]
base = "light"
