
AZURE_STORAGE_CONNECTION_STRING="DefaultEndpointsProtocol=https;AccountName=pentacapstonefiles;AccountKey=sZrih565Ul5ZniPes4JiBhRuwPVW3PZoCs06g6rlIGgx4pVqXsM3Y9T6sZqvIlALkA2USdYKxdaT+AStBqV/nA==;EndpointSuffix=core.windows.net"
CONTAINER_NAME="capstone"
AZURE_CONTAINER="capstone"
FINAL_DATA_BLOB_PATH="data/processed/final_model_dataset.csv"
ATTR_DATA_BLOB_PATH="data/processed/attribution_all_scored.csv"
